sonar.projectKey=cloudcommerce-backend
sonar.projectName=CloudCommerce Backend

sonar.sources=app/backend/src
sonar.tests=app/backend/tests

sonar.javascript.lcov.reportPaths=app/backend/coverage/lcov.info
