apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.frontend.config.configMapName }}
  labels:
    app: frontend

data:
  {{- range $key, $value := .Values.frontend.config.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
