apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  labels:
    app: backend

spec:
  replicas: {{ .Values.backend.replicas }}

  strategy:
    type: {{ .Values.backend.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.backend.strategy.maxUnavailable }}
      maxSurge: {{ .Values.backend.strategy.maxSurge }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      nodeSelector:
        {{- toYaml .Values.backend.nodeSelector | nindent 8 }}

      serviceAccountName: {{ .Values.backend.serviceAccount.name }}

      terminationGracePeriodSeconds: 30

      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ .Values.backend.config.configMapName }}

            - secretRef:
                name: {{ .Values.backend.config.secretName }}

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

          startupProbe:
            httpGet:
              path: {{ .Values.backend.probes.startup.path }}
              port: http
            failureThreshold: {{ .Values.backend.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.backend.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.startup.timeoutSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: http
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.probes.liveness.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: http
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.probes.readiness.failureThreshold }}
