{{- if .Values.backend.hpa.enabled }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: backend-hpa
  labels:
    app: backend

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend

  minReplicas: {{ .Values.backend.hpa.minReplicas }}
  maxReplicas: {{ .Values.backend.hpa.maxReplicas }}

  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.backend.hpa.behavior.scaleUp.stabilizationWindowSeconds }}

    scaleDown:
      stabilizationWindowSeconds: {{ .Values.backend.hpa.behavior.scaleDown.stabilizationWindowSeconds }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.hpa.cpu.targetUtilization }}

{{- end }}
